### ISSUE TITLE
Deluge not downloading

### ISSUE THREAD

**Issue by mickyyman** [Rick45/quick-arr-Stack#1]
Hi there,

I hope I'm not bothering you here...

I followed every step (without VPN) but somehow deluge won't download anything.

This is the log from Docker.

`deluge  | 20:34:49 [INFO    ][deluge.core.rpcserver         :1622] Deluge Client connection made from: 127.0.0.1:34448
deluge  | 20:34:49 [WARNING ][deluge.config                 :477 ] Unable to open config file: /config/label.conf because: [Errno 2] No such file or directory: '/config/label.conf'
deluge  | 20:34:49 [WARNING ][deluge.config                 :502 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/label.conf'
deluge  | 20:56:28 [INFO    ][deluge.core.torrentmanager    :1622] Torrent testfile from user "localclient" added
deluge  | 20:56:28 [WARNING ][deluge.core.torrentmanager    :1622] Torrent id not in torrents loading list: 'xxxxxxxxxxxxx'
deluge  | 20:56:45 [WARNING ][deluge.httpdownloader      :1622] Error occurred downloading file from "http://xxxxxx/": DNS lookup failed: no results for hostname lookup: xxxxx.
deluge  | 20:56:50 [WARNING ][deluge.httpdownloader      :1622] Error occurred downloading file from "http://all/": DNS lookup failed: no results for hostname lookup: all.`

I've tried this setup on a VM, Remote server and local. but get this error in all cases. Hoping you can help a bit here.

Kind regards.

**Comment by Rick45** [comment]
Hi, are you able to open the deluge UI and see the torrents?

**Comment by mickyyman** [comment]
> Hi, are you able to open the deluge UI and see the torrents?

Yes. I can access the UI and the torrent shows. I've also checked if the tracker is actually online which it is.

**Comment by Rick45** [comment]
that looks like the DNS lookup does not work, I have some issues like that one without VPN if I use the DNS from my ISP, as they block all the major torrent sites. are you using it or a DNS like google or Cloudflare?

are you able to download something like the Ubuntu distro like [https://releases.ubuntu.com/22.04/ubuntu-22.04.3-desktop-amd64.iso.torrent](https://releases.ubuntu.com/22.04/ubuntu-22.04.3-desktop-amd64.iso.torrent)?
