### ISSUE TITLE
Deluge not uploading

### ISSUE THREAD

**Issue by Bodyes26** [Rick45/quick-arr-Stack#2]
Hi man, sorry to bother but idk where to ask, I'm having problem setting deluge. I've set it up with the VPN and download works fine, but it isn't uploading anything. from deluge settings i don't see anything that's blocking but idk if I need to open more ports on the vpn container, for example. can you help me? even a DM is fine for me, thanks a lot!

**Comment by Rick45** [comment]
That could be multiple things, but most likely related to the VPN provider.
I also didn't get much upload. Then, on my pvn provider, I subscribed to the port-forward plugin, and it improved a bit; I didn't bother much with it.
